### PR TITLE
Use krkn home dir instead of tmp

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Review by shahsahil264 — APPROVED** [review]
LGTM

**Comment by paigerube14** [comment]
I don't think we have write access in the krkn_loc path since it's in root. What is the current error we are seeing

**Comment by chaitanyaenr** [comment]
> I don't think we have write access in the krkn_loc path since it's in root. What is the current error we are seeing

Hi @paigerube14 we recently switched from root user to krkn user in the base image to run as non-privileged container: https://github.com/krkn-chaos/krkn/blob/main/containers/Dockerfile#L40

**Pull request merged**
